name: 'akrion_ecommerce'
version: '1.0.0'
config-version: 2

# This must match the top line of your ~/.dbt/profiles.yml
profile: 'akrion_ecommerce'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

# SEED CONFIGURATION
seeds:
  +quote_columns: false

# MODEL CONFIGURATION
models:
  akrion_ecommerce:
    # Use Case 2 Configuration
    use_case_2:
      +materialized: table

    # Use Case 3 Configurations (Properly nested)
    staging:
      +materialized: view
      +schema: staging      
    intermediate:
      +materialized: table
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts